volumes:
  files:
    driver: local
  mysql:
    driver: local
  backup:
    driver: local
  redis:
    driver: local

services:
  ownlcoud:
    image: owncloud/server:${OWNCLOUD_VERSION}
    restart: always
    depends_on:
      - db
      - redis
      - traefik-reverse-proxy
    environment:
      - OWNCLOUD_DOMAIN=${OWNCLOUD_DOMAIN}  # Required for proxy access. Must match proxy routing rule
      - OWNCLOUD_TRUSTED_DOMAINS=${OWNCLOUD_DOMAIN},localhost
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloudMARIA
      - OWNCLOUD_DB_HOST=db
      - OWNCLOUD_ADMIN_USERNAME=${ADMIN_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OWNCLOUD_UTF8MB4_ENABLED=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.owncloud.rule=Host(`${OWNCLOUD_DOMAIN}`)"
      - "traefik.http.services.owncloud.loadbalancer.server.port=8080"
      # DEBUG
      - "traefik.http.routers.owncloud.entrypoints=websecure"
      - "traefik.http.routers.owncloud.tls=true"      
    networks:
      - traefik-network
      - internal
    volumes:    
      - "${HOST_OWNCLOUD_DATA_PATH}:/mnt/data"

  db:
    image: webhippie/mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=owncloudMARIA
      - MARIADB_USERNAME=owncloud
      - MARIADB_PASSWORD=owncloudMARIA
      - MARIADB_DATABASE=owncloud
      - MARIADB_MAX_ALLOWED_PACKET=128M
      - MARIADB_INNODB_LOG_FILE_SIZE=64M
      - MARIADB_INNODB_LARGE_PREFIX=ON
      - MARIADB_INNODB_FILE_FORMAT=Barracuda
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:      
      - "${HOST_OWNCLOUD_DB_MYSQL_PATH}:/var/lib/mysql"
      - "${HOST_OWNCLOUD_DB_BACKUP_PATH}:/var/lib/backup"
    networks:
      - internal

  redis:
    image: webhippie/redis:latest
    restart: always
    environment:
      - REDIS_DATABASES=1
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:    
      - "${HOST_OWNCLOUD_REDIS_PATH}:/var/lib/redis"
    networks:
      - internal